on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: leafo/gh-actions-lua@v11
      - uses: leafo/gh-actions-luarocks@v5

      - name: make build
        run: make build

      - name: make test
        run: make test
